### ISSUE TITLE
Ionic CodePush failure: no such file or directory, lstat './platforms/android/assets/www/'

### ISSUE THREAD

**Issue by dc165015** [DLopezOpentix/example-cordova-code-push-plugin#3]
I followed the official ionic codepush example.

It used the platforms/android/assets/www folder, but there is neither assets folder, nor www folder under platforms/android in my project.

I also tried: ionic build, ionic cordova build android, ionic cordova prepare android. They are the same. The assets folder wasn't created at all.

Where I can solve this problem?

**Comment by rromantp** [comment]
use **./platforms/android/app/src/main/assets/www/ **. Make sure to use --prod --release flags so sourcemaps are not generated

**Comment by rromantp** [comment]
> I followed the official ionic codepush example.
> 
> It used the platforms/android/assets/www folder, but there is neither assets folder, nor www folder under platforms/android in my project.
> 
> I also tried: ionic build, ionic cordova build android, ionic cordova prepare android. They are the same. The assets folder wasn't created at all.
> 
> Where I can solve this problem?

use **./platforms/android/app/src/main/assets/www/** . Make sure to use --prod --release flags so sourcemaps are not generated

**Comment by Dellos7** [comment]
Hello!

It seems that the cordova-android asset path changed in version 7. See https://github.com/ionic-team/ionic-app-scripts/issues/1380. So if you are using a version >= 7 for the `cordova-android` package then the asset folder will be as @rromantp said: `./platforms/android/app/src/main/assets/www`.

I'm going to update the readme so it's updated.

Thank you!
